name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define common steps as an anchor
common-steps: &common-steps
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Install uv
    uses: astral-sh/setup-uv@v5
    with:
      cache-dependency-glob: "uv.lock"
      enable-cache: true
      python-version: "3.10"
      version: "0.7.2"

  - name: Install dependencies
    run: uv sync --dev --locked

jobs:
  ruff-format:
    name: Format code with ruff
    runs-on: ubuntu-latest

    steps:
      - <<: *common-steps
      - name: Run ruff format
        run: uv run ruff format --check --diff

  ruff-check:
    name: Check code with ruff
    runs-on: ubuntu-latest

    steps:
      - <<: *common-steps
      - name: Run ruff check
        run: uv run ruff check --diff --fix-only --exit-non-zero-on-fix

  mypy-check:
    name: Check code with mypy
    runs-on: ubuntu-latest

    steps:
      - <<: *common-steps
      - name: Run mypy check
        run: uv run mypy src

  test:
    name: Test on ${{ matric.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "uv.lock"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "0.7.2"

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run tests
        run: uv run pytest
